services:
  lerama:
    image: ghcr.io/altendorfme/lerama:latest
    container_name: lerama
    environment:
      TZ: ${TZ:-UTC}
      APP_URL: https://lerama.lab
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_DATABASE: lerama
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    ports:
      - 80:80
    volumes:
      - ./lerama/storage:/app/public/storage
    restart: unless-stopped
    networks:
      - lerama
networks:
  lerama:
    driver: bridge