SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `feeds`
ADD COLUMN IF NOT EXISTS `shuffle` tinyint(1) UNSIGNED NOT NULL DEFAULT 1 AFTER `proxy_only`;

ALTER TABLE `feeds`
ADD INDEX IF NOT EXISTS `idx_shuffle`(`shuffle`) USING BTREE;

SET FOREIGN_KEY_CHECKS = 1;
