#!/command/with-contenv sh

if [ "${LERAMA_SCHEDULER:-true}" != "true" ]; then
    echo "[lerama] scheduler desabilitado por LERAMA_SCHEDULER"
    exit 0
fi

cd /var/www/html || exit 1

trap 'exit 0' TERM INT

while :; do
    php artisan schedule:run --no-interaction
    sleep $((60 - $(date +%S | sed 's/^0//'))) &
    wait $!
done
