ALTER TABLE `feeds` 
ADD COLUMN IF NOT EXISTS `retry_count` INT UNSIGNED DEFAULT 0,
ADD COLUMN IF NOT EXISTS `retry_proxy` TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS `paused_at` DATETIME DEFAULT NULL;